name: Run Symfony Tests and Notify by Email

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1: Récupérer le code du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # Étape 2: Installer PHP avec les extensions requises pour Symfony
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Symfony 7 utilise PHP 8.2
        extensions: mbstring, intl, pdo, sqlite, zip

    # Étape 3: Installer les dépendances via Composer
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Étape 4: Exécuter les tests PHPUnit
    - name: Run tests
      run: |
        php bin/phpunit --log-junit tests/report.xml
      continue-on-error: true  # Continue même si les tests échouent

    # Étape 5: Sauvegarder les résultats des tests en tant qu'artefact
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: tests/report.xml

    # Étape 6: Installer les utilitaires d'envoi d'emails (mailutils)
    - name: Install mailutils
      run: sudo apt-get install -y mailutils

    # Étape 7: Envoyer un email avec les résultats des tests
    - name: Send email notification
      if: always()  # Cette étape s'exécute toujours, même si les tests échouent
      run: |
        cat tests/report.xml | mail -s "Test Results for Symfony" hello@agiliteach.org
